import { Platform, StatusBar, StyleSheet } from 'react-native';

// ═══ SPPERO v3 · Sunrise Theme · Light & Vibrant ═════════════════════════════
export const C = {
  // ── Brand ──────────────────────────────────────────────────────────────────
  pink:    '#FF2D78',
  yellow:  '#F59E0B',   // amber — readable on white
  green:   '#059669',   // emerald — readable on white
  red:     '#EF4444',
  purple:  '#7C3AED',

  // ── Backgrounds ────────────────────────────────────────────────────────────
  bg:      '#F7F8FF',   // near-white lavender
  bgCard:  '#FFFFFF',   // pure white cards
  bgDeep:  '#EEF0FF',   // deeper lavender for hero sections

  // ── "Glass" → now light card tokens ────────────────────────────────────────
  glass:        '#FFFFFF',
  glassMid:     '#F3F4FE',
  glassHigh:    '#EAECFD',
  glassBorder:  '#E4E6F6',
  glassB2:      '#D8DCF4',

  // ── Tinted fills ────────────────────────────────────────────────────────────
  pinkGlass:    'rgba(255,45,120,0.07)',
  pinkBorder:   'rgba(255,45,120,0.25)',
  yellowGlass:  'rgba(245,158,11,0.08)',
  yellowBorder: 'rgba(245,158,11,0.30)',
  greenGlass:   'rgba(5,150,105,0.08)',
  greenBorder:  'rgba(5,150,105,0.28)',
  redGlass:     'rgba(239,68,68,0.08)',
  redBorder:    'rgba(239,68,68,0.28)',
  purpleGlass:  'rgba(124,58,237,0.08)',
  purpleBorder: 'rgba(124,58,237,0.28)',

  // ── Text ────────────────────────────────────────────────────────────────────
  text:      '#1A1A2E',
  textMuted: '#64748B',
  textDim:   '#94A3B8',
};

export const s = StyleSheet.create({
  // ── Screen ────────────────────────────────────────────────────────────────
  screen: { flex: 1, backgroundColor: C.bg },

  // ── Top bar ───────────────────────────────────────────────────────────────
  topBar: {
    backgroundColor: C.pink,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 28) + 10 : 54,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
    elevation: 6,
    shadowColor: C.pink,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  topTitle: { color: '#fff', fontSize: 17, fontWeight: '900', flex: 1, textAlign: 'center', letterSpacing: 0.2 },
  greeting: { color: C.text, fontSize: 15, fontWeight: '700' },
  subTxt:   { color: C.textMuted, fontSize: 11, marginTop: 2 },

  // ── Card ──────────────────────────────────────────────────────────────────
  card: {
    margin: 14,
    backgroundColor: C.bgCard,
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: C.glassBorder,
    elevation: 4,
    shadowColor: C.pink,
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
  },

  // ── Hero ──────────────────────────────────────────────────────────────────
  hero: {
    backgroundColor: C.bgCard,
    alignItems: 'center',
    paddingVertical: 36,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: C.glassBorder,
  },
  heroTitle: { color: C.text, fontSize: 24, fontWeight: '800', marginTop: 8 },
  heroSub:   { color: C.textMuted, fontSize: 13, marginTop: 5, textAlign: 'center' },

  // ── Input ─────────────────────────────────────────────────────────────────
  input: {
    borderWidth: 1.5,
    borderColor: C.glassBorder,
    borderRadius: 14,
    padding: 14,
    fontSize: 14,
    backgroundColor: C.bgCard,
    marginBottom: 10,
    color: C.text,
  },
  label: { fontSize: 13, fontWeight: '600', color: C.textMuted, marginBottom: 6 },
  flag: {
    fontSize: 13,
    padding: 12,
    backgroundColor: C.glassMid,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: C.glassBorder,
    marginRight: 8,
    color: C.text,
  },

  // ── Buttons ───────────────────────────────────────────────────────────────
  btn: {
    backgroundColor: C.pink,
    borderRadius: 16,
    padding: 17,
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 6,
    elevation: 6,
    shadowColor: C.pink,
    shadowOpacity: 0.38,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  btnTxt:   { color: '#fff', fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
  err:      { textAlign: 'center', color: C.red, fontWeight: '700', marginBottom: 8 },
  back:     { textAlign: 'center', color: C.purple, marginTop: 14, fontSize: 13, fontWeight: '600' },
  applyBtn: {
    padding: 12,
    borderWidth: 1.5,
    borderColor: C.pink,
    borderRadius: 10,
    justifyContent: 'center',
    marginLeft: 8,
    backgroundColor: C.pinkGlass,
  },

  // ── Layout ────────────────────────────────────────────────────────────────
  row:         { flexDirection: 'row', alignItems: 'center' },
  backBtn:     { width: 36, alignItems: 'flex-start' },
  sheetHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: C.glassBorder, alignSelf: 'center', marginBottom: 12 },
  navFloat:    { position: 'absolute', bottom: 0, left: 0, right: 0 },

  // ── Avatar ────────────────────────────────────────────────────────────────
  avatar:    { width: 40, height: 40, borderRadius: 20, backgroundColor: C.pink, alignItems: 'center', justifyContent: 'center' },
  avatarTxt: { color: '#fff', fontWeight: '800', fontSize: 17 },

  // ── Search ────────────────────────────────────────────────────────────────
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.bgCard,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    elevation: 4,
    shadowColor: C.pink,
    shadowOpacity: 0.10,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    borderWidth: 1.5,
    borderColor: C.glassBorder,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.bgCard,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.glassBorder,
  },
  searchIcon: { fontSize: 18, marginRight: 10 },
  searchPh:   { color: C.textMuted, fontSize: 14, flex: 1 },
  mapFit:     { height: 260, width: '100%', backgroundColor: '#E0EEFF' },

  // ── Quick actions ─────────────────────────────────────────────────────────
  quickRow: { flexDirection: 'row', gap: 10, marginBottom: 14 },
  quickBtn: {
    flex: 1,
    backgroundColor: C.bgCard,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    elevation: 3,
    borderWidth: 1,
    borderColor: C.glassBorder,
    shadowColor: C.pink,
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  quickIcon: { fontSize: 22 },
  quickLbl:  { fontSize: 10, color: C.textMuted, marginTop: 5, fontWeight: '600' },

  // ── Section title ─────────────────────────────────────────────────────────
  secTitle: { fontSize: 14, fontWeight: '800', color: C.text, marginBottom: 10, marginTop: 4 },

  // ── History ───────────────────────────────────────────────────────────────
  histCard: {
    backgroundColor: C.bgCard,
    borderRadius: 18,
    padding: 16,
    marginBottom: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: C.glassBorder,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
  },
  histIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.pinkGlass,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    borderWidth: 1,
    borderColor: C.pinkBorder,
  },
  recentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.bgCard,
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: C.glassBorder,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
  },
  recentRoute: { fontSize: 13, fontWeight: '700', color: C.text },
  recentDate:  { fontSize: 11, color: C.textMuted, marginTop: 2 },
  recentFare:  { fontSize: 14, fontWeight: '800', color: C.yellow },

  // ── Profile ───────────────────────────────────────────────────────────────
  profileHero: {
    backgroundColor: C.bgCard,
    borderRadius: 22,
    padding: 24,
    alignItems: 'center',
    marginBottom: 14,
    elevation: 4,
    borderWidth: 1,
    borderColor: C.glassBorder,
    shadowColor: C.pink,
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: C.pink,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    elevation: 8,
    shadowColor: C.pink,
    shadowOpacity: 0.40,
    shadowRadius: 14,
    borderWidth: 3,
    borderColor: 'rgba(255,45,120,0.3)',
  },
  profileName:  { color: C.text, fontSize: 20, fontWeight: '800' },
  profilePhone: { color: C.textMuted, fontSize: 13, marginTop: 3 },
  badge: {
    backgroundColor: C.yellowGlass,
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 14,
    marginTop: 8,
    borderWidth: 1,
    borderColor: C.yellowBorder,
  },

  // ── Promo ─────────────────────────────────────────────────────────────────
  promoBanner: {
    backgroundColor: C.pinkGlass,
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
    elevation: 2,
    borderWidth: 1,
    borderColor: C.pinkBorder,
  },
  promoTxt: { color: C.text, fontSize: 13, textAlign: 'center', fontWeight: '600' },

  // ── Bottom nav ────────────────────────────────────────────────────────────
  nav: {
    flexDirection: 'row',
    paddingBottom: Platform.OS === 'android' ? 44 : 16,
    paddingTop: 10,
    elevation: 16,
    shadowColor: C.pink,
    shadowOpacity: 0.10,
    shadowRadius: 16,
  },
  navItem:   { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navIcon:   { fontSize: 22, color: C.textDim },
  navLbl:    { fontSize: 10, color: C.textDim, marginTop: 3, letterSpacing: 0.3 },
  navActive: { color: C.pink, fontWeight: '800' },

  // ── Wallet ────────────────────────────────────────────────────────────────
  walletCard: {
    backgroundColor: C.pink,
    borderRadius: 20,
    padding: 20,
    marginBottom: 12,
    elevation: 8,
    shadowColor: C.pink,
    shadowOpacity: 0.40,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
  },

  // ── Menu ──────────────────────────────────────────────────────────────────
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.bgCard,
    borderRadius: 16,
    padding: 14,
    marginBottom: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: C.glassBorder,
  },
  menuIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: C.pinkGlass,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: C.pinkBorder,
  },
  logoutBtn: {
    borderWidth: 1.5,
    borderColor: C.red,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 24,
    backgroundColor: C.redGlass,
  },

  // ── Suggestions ───────────────────────────────────────────────────────────
  suggBox: {
    backgroundColor: C.bgCard,
    borderRadius: 14,
    marginTop: 4,
    elevation: 18,
    borderWidth: 1,
    borderColor: C.glassBorder,
    zIndex: 99,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  suggItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.glassBorder,
  },

  // ── Driver card ───────────────────────────────────────────────────────────
  driverCard: {
    backgroundColor: C.bgCard,
    borderRadius: 18,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.glassBorder,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  driverAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: C.glassMid,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 2,
    borderColor: C.pink,
  },
  driverName: { fontSize: 15, fontWeight: '800', color: C.text },

  // ── OTP card ──────────────────────────────────────────────────────────────
  otpCard: {
    backgroundColor: C.bgCard,
    borderRadius: 18,
    padding: 20,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: C.pinkBorder,
    elevation: 4,
    shadowColor: C.pink,
    shadowOpacity: 0.12,
    shadowRadius: 10,
  },

  // ── Fare / info ───────────────────────────────────────────────────────────
  fareCard: {
    backgroundColor: C.bgCard,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.glassBorder,
    elevation: 2,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: C.bgCard,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.glassBorder,
    elevation: 2,
  },
  actionBtn: { alignItems: 'center', padding: 4, flex: 1 },

  // ── Chat ──────────────────────────────────────────────────────────────────
  chatBadge: {
    position: 'absolute',
    top: -6,
    right: -10,
    backgroundColor: C.pink,
    borderRadius: 9,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  chatAlert: {
    backgroundColor: C.pinkGlass,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: C.pinkBorder,
  },
  infoBox: {
    backgroundColor: C.greenGlass,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.greenBorder,
  },
  chatBubble: { maxWidth: '75%', borderRadius: 16, padding: 12, marginBottom: 8 },
  chatMine:   { backgroundColor: C.pink, alignSelf: 'flex-end', borderBottomRightRadius: 4 },
  chatTheirs: {
    backgroundColor: C.glassMid,
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: C.glassBorder,
  },
  chatInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    paddingBottom: 28,
    backgroundColor: C.bgCard,
    borderTopWidth: 1,
    borderTopColor: C.glassBorder,
  },
  chatInput: {
    flex: 1,
    backgroundColor: C.glassMid,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    marginRight: 8,
    color: C.text,
    borderWidth: 1,
    borderColor: C.glassBorder,
  },
  chatSend: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: C.pink,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: C.pink,
    shadowOpacity: 0.40,
    shadowRadius: 8,
  },

  // ── Payment ───────────────────────────────────────────────────────────────
  payBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    padding: 18,
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    borderWidth: 1.5,
    borderColor: C.glassBorder,
    backgroundColor: C.bgCard,
  },
  scratchCard: { borderRadius: 20, padding: 24, alignItems: 'center', marginBottom: 4, elevation: 6 },
  tipBtn: {
    flex: 1,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: C.glassBorder,
    alignItems: 'center',
    backgroundColor: C.bgCard,
  },

  // ── Stats ─────────────────────────────────────────────────────────────────
  statBox: {
    flex: 1,
    backgroundColor: C.bgCard,
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    elevation: 2,
    borderWidth: 1,
    borderColor: C.glassBorder,
  },
  statNum: { fontSize: 24, fontWeight: '800', color: C.yellow },
  statLbl: { fontSize: 11, color: C.textMuted, marginTop: 4 },
});
